### ISSUE TITLE
Bold Highlighting will go past closing tag if there is no space.

### ISSUE THREAD

**Issue by TheElementalOfDestruction** [nwhetsell/language-rtf#1]
RTF that does not have a space after a closing bold tag (i.e. \b0) will have the hold highlighting continue until it meets some tag that it properly recognizes to end the bold. From the specification, not having a space after a tag is valid if the last character of the tag is a number and the character immediately afterwards is not a number (i.e. `\b Some text \b0Some more text` would be perfectly valid).

Example code:
```rtf
{\b Some text \b0Some more text}
```

Expected result:
I would expect the closing bold tag and the tag after it to not be highlighted as bold.

Actual result:
Apparently the highlighting for GitHub actually has the same problem, so you can see it in my example text.

**Comment by nwhetsell** [comment]
Thanks for the report; in what section of [version 1.9.1 of the RTF spec](https://web.archive.org/web/20190708132914/http://www.kleinlercher.at/tools/Windows_Protocols/Word2007RTFSpec9.pdf) does it say that things like `\b0` needn’t be followed by a space?

> Apparently the highlighting for GitHub actually has the same problem…

GitHub Linguist currently [uses the grammar in this repository](https://github.com/github/linguist/tree/80f3531e8a1014a23f4606458e5a528053ed3cac/vendor) to highlight RTF files, so this is expected.

**Comment by TheElementalOfDestruction** [comment]
The introduction section, on control words. On page 8:
![image](https://user-images.githubusercontent.com/24580325/149214121-7ef8c60b-92ba-4d07-b379-b9d3d5f4f6eb.png)

Edit: I only know this so readily because I specifically had to add handling for this when I was writing a parser.

**Comment by nwhetsell** [comment]
Got it, thanks!

**Comment by nwhetsell** [comment]
This should now be fixed, thanks again for the report!

This issue will exist on GitHub until Linguist is updated, but in the meantime you can see the grammar working (correctly) on Lightshow:

https://github-lightshow.herokuapp.com/?utf8=✓&scope=from-url&grammar_format=auto&grammar_url=https%3A%2F%2Fraw.githubusercontent.com%2Fnwhetsell%2Flanguage-rtf%2F0f11935ceb9903e794d59b598d7bf72d0053d8c7%2Fgrammars%2Frtf.cson&grammar_text=&code_source=from-text&code_url=&code=%7B%5Cb+Some+text+%5Cb0Some+more+text%7D
